In [1]:
import numpy as np

machine learning - is learning on data to make predictions. pattern recognition over data, so future predictions can be made

## NumPy Arrays

In [2]:
# Using np.array()
arr1 = np.array([1, 2, 3, 4, 5])
display(arr1)

array([1, 2, 3, 4, 5])

```np.arange(start, end, step)```

If the ```start``` parameter doesn't have an argument, its default value is 0

If the ```step``` parameter doesn't have an argument, its default value is 1


In [3]:
# Using np.arange()
arr2 = np.arange(11)
display(arr2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

```np.linspace(start, stop, num)```

Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

In [4]:
# Using np.linspace()
arr3 = np.linspace(0, 10, 5)
display(arr3)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

By default, its dtype is set to float. But we can change the dtype to int, char, and etc.

In [5]:
arr4 = np.linspace(1, 20, 5, dtype=int)
display(arr4)

array([ 1,  5, 10, 15, 20])

## More on NumPy Arrays
```np.zeros()``` - Return a new array of given shape and type, filled with zeros.

```np.empty()``` - Return a new array of given shape and type, without initializing entries.

```np.ones()``` - Return a new array of given shape and type, filled with ones.

```np.random.rand()``` - Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [6]:
# np.zeros()
zeros_arr = np.zeros(5, dtype=int)
display(zeros_arr)

array([0, 0, 0, 0, 0])

In [7]:
# np.empty()
empty_arr = np.empty(5)
display(empty_arr)

array([ 1.,  5., 10., 15., 20.])

In [8]:
ones_arr = np.ones(5, dtype=int)
display(ones_arr)

array([1, 1, 1, 1, 1])

## Multi-dimensional Array

In [9]:
# Create a 2d-array using np.array()
two_d_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
display(two_d_arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

```np.reshape()```

In [10]:
one_d_arr = np.array([1, 2, 3, 4, 5, 6])

multi_d_arr = np.reshape(one_d_arr, (2, 3))

display(multi_d_arr)

array([[1, 2, 3],
       [4, 5, 6]])

## Size, Shape, Dimension
```.size``` - number of elements in the array

```.shape``` - tuple-based refers to the columns and rows

```.ndim``` - number of dimension of the array

In [11]:
display(multi_d_arr)
display(multi_d_arr.size)

array([[1, 2, 3],
       [4, 5, 6]])

6

In [12]:
display(multi_d_arr)
display(multi_d_arr.shape)

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

In [13]:
display(multi_d_arr)
display(multi_d_arr.ndim)

array([[1, 2, 3],
       [4, 5, 6]])

2

## Array Math Operations

In [14]:
a = np.array([1, 1])
b = np.array([2, 1])

addition = np.add(a, b)
subtraction = np.subtract(a, b)
multiplication = np.multiply(a, b)
division = np.divide(a, b)

print(f'Addition: {addition}')
print(f'Subtraction: {subtraction}')
print(f'Multiplication: {multiplication}')
print(f'Division: {division}')

Addition: [3 2]
Subtraction: [-1  0]
Multiplication: [2 1]
Division: [0.5 1. ]


## Multiplying Vector with a Scalar

In [15]:
vector = np.array([10, 8])
vector * 1.5

array([15., 12.])

## Indexing and Slicing

In [16]:
display(arr1)
display(arr1[2])

# first element
display(arr1[0])

array([1, 2, 3, 4, 5])

3

1

In [17]:
display(multi_d_arr)
display(multi_d_arr[0])
display(multi_d_arr[1])

# access element
display(multi_d_arr[1][1])

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3])

array([4, 5, 6])

5

## Slicing
```arr[start : end : step]```

In [18]:
display(arr1)

# get [2,3,4]
display(arr1[1:4])

array([1, 2, 3, 4, 5])

array([2, 3, 4])

In [19]:
display(arr1)

# get [1,2,3]
display(arr1[:3])

array([1, 2, 3, 4, 5])

array([1, 2, 3])

In [20]:
display(arr1)

# get [1, 3, 5]
display(arr1[::2])

# get [2, 4]
display(arr1[1::2])

array([1, 2, 3, 4, 5])

array([1, 3, 5])

array([2, 4])

In [21]:
# 2d array
display(two_d_arr)

# get the last row
display(two_d_arr[-1]) 
# or
display(two_d_arr[2:3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([7, 8, 9])

array([[7, 8, 9]])

```two_d_arr[-1]``` returns a 1D array containing the elements of the last row.

```two_d_arr[2:3]``` returns a 2D array that contains a single row (the third row in this case) wrapped in an additional array due to the slice format.

## Stacking

In [22]:
a1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a2 = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

display(a1)
display(a2)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
vert_stack = np.vstack((a1, a2))
display(vert_stack)
display(vert_stack.ndim)
display(vert_stack.size)
display(vert_stack.shape)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

2

20

(4, 5)

In [24]:
horiz_stack = np.hstack((a1, a2))
display(horiz_stack)
display(horiz_stack.ndim)
display(horiz_stack.size)
display(horiz_stack.shape)

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

2

20

(2, 10)